### ISSUE TITLE
some question about the code in line 108 and 178

### ISSUE THREAD

**Issue by zzz123xyz** [michelbl/MPPCA#1]
Dear Michel Blancard 
    My name is Lance Liu, I'm a student at the University of Queensland. I found your code of MPPCA is very interesting and helpful. 
    But I have some questions about it on Line 108 and 178, I didn't really find the counterparts in the paper, When it comes to computing Rni, I found it is another form in the paper.
    More importantly, I try to compute the p(t_n) probability of MPPCA for each sample t_n. But when I do this, I fail to get the reasonable results because of the |C| = 0 in the code. The |C| is in Equ. (6) in the paper.
Could you please help me with that, Thanks so much 
Best regards 

Lance (LiangChen) Liu 
School of ITEE 
University of Queensland
Australia

**Comment by michelbl** [comment]
Dear Lance,

Thank you very much for your interest for this code. I am very glad it you found it helpful.

Line 108 and 178 is what I talk about in the README : "In high dimensions, a logarithmic representation of numbers was required to avoid underflows." In high dimensions (say, 1000), you have to deal with very tiny numbers, like exp(-10000). These numbers cannot be stored with standard python (or C, or Java...) number representations which lack this degree of precision. The technical terms for this issue is "arithmetic underflow", see https://en.wikipedia.org/wiki/Arithmetic_underflow

The trick is to compute and store their logarithm. In case of exp(-10000), this is -10000 which is a perfectly fine number that won't underflow to zero.

I think the problem about |C|=0 has the same root. Because the dimension of the matrix is high, the determinent underflows to zero. In fact, if you find |C|=0 while C is supposed to be invertible, this is a certain symptom of underflow... ;)

If you need |C| for your application, you need a way to compute the logarithm of |C|, not |C| itself. Or you may prefer to use an arbitrary floating point number library, but the performance could suffer.

Please keep me updated about your research. Don't hesitate to ask questions if I can be of any help.

Best regards
Michel

**Comment by zzz123xyz** [comment]
Thanks very much for your reply dear Michel
    I tried the way you suggested, but I didn't find a way to compute the log(|C|) without computing |C| at first, the problem still exists. Actually, I just want to compute the p(t_n) probability of MPPCA for each sample t_n, I find some cues here in Line 119 that computes L[i].
    I think I can compute p(t_n)_c  of  one PPCA (c is the index of the cluster) as follow,  Therefore the final p(t_n) probability of MPPCA is like p_final = p_final + ptn[:, c] \* pi[c]
 But final result is not a probability. Many elements in ptn is far larger than 1. 

 Ltn[:, c] = (
            (myMax.ravel() + np.log(np.exp(logR - myMax).sum(axis=1))) #why we need myMax.ravel()
            - d \* np.log(2 \* 3.141593) / 2.
        )
        ptn[:, c] = np.exp(Ltn[:, c])
p_final = p_final + ptn[:, c] \* pi[c]
Could you tell me how to compute the p(t_n) probability of MPPCA for each sample t_n. I'm still quiet comfused about this. Thank you so much..
Best regards

Lance (LiangChen) Liu 
School of ITEE 
University of Queensland
Australia

**Comment by michelbl** [comment]
1. Do you really need to compute|C| (or log(|C|)) ? In many applications, computing a quantity proportional to p(t_n), not p(t_n) itself, is enough. If I remember well, this is the case in the paper (see eq 21).
2. why we need myMax.ravel() ?
   (myMax.ravel() + np.log(np.exp(logR - myMax).sum(axis=1))) is equivalent to np.log(np.exp(logR).sum(axis=1)). But if you compute the latter in high dimensions, results will be highly inaccurate because of overflow/underflow.
3. If you need to compute a determinant in high dimension, you may want to search about log-determinent to avoid underflow.
4. To write our implementation, we first wrote on paper the equations we needed to compute everything we wanted. Then we wrote an implementation without caring about underflow/overflow. We tested it with data on small dimensions. Then we noticed it went wrong on high dimensions. After we diagnosed a problem of underflow/overflow, we adapted our implementation with log representations, and tested its result against our first implementation. I suggest you follow the same steps and not stick too closely with our implementation if you are not comfortable with log representations right now.

Hope this helps

**Comment by zzz123xyz** [comment]
Dear Michel
    Sorry for late reply, really busy recently, your suggestion is very helpful. The code is still a little mysterious to me,  but I think I can figure it out now following your suggestion, I will let you know if I run into some other problems. 
Thanks very 
Lance 
best regard
